CREATE TABLE IF NOT EXISTS blog_posts (
    id SERIAL PRIMARY KEY,

    slug TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    md_content TEXT NOT NULL,
    html_content TEXT NOT NULL,

    published BOOLEAN NOT NULL DEFAULT FALSE,
    published_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    views INT NOT NULL DEFAULT 0,
    edited_time TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS github_users (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    url TEXT NOT NULL,
    admin BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS github_tokens (
    access_token TEXT NOT NULL PRIMARY KEY,
    user_id INTEGER NOT NULL UNIQUE,
    created_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (user_id) REFERENCES github_users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS guestbook_posts (
    id SERIAL PRIMARY KEY,

    user_id INTEGER NOT NULL,
    content TEXT NOT NULL,
    published BOOLEAN NOT NULL,
    created_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (user_id) REFERENCES github_users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS csrf_tokens (
    csrf_token TEXT NOT NULL PRIMARY KEY UNIQUE,
    redirect_to TEXT NOT NULL,
    created_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

